

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/backgammon
    username: db_user
    password: 123qwe


  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: backgammon

backgammon:
  app:
    jwtExpirationMs: '1000000000'
    jwtCookieName: 'jwt-cookie'
    jwtSecret: back-gammon-socket-game

server:
  port: 8081

rt-server:
  port: '9092'
  host: localhost
