

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backgammon
    username: db_user
    password: 123qwe

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: backgammon

google:
  client:
    clientId: <Google OAuth 2.0 Client ID>
    clientSecret: <Google OAuth 2.0 Client Secret>
    redirectUri: <Google OAuth 2.0 Authorized redirect URIs>
  auth:
    tokenServerUrl: https://oauth2.googleapis.com/token
    authorizationServerUrl: https://accounts.google.com/o/oauth2/v2/auth

backgammon:
  app:
    jwtExpirationMs: '1000000000'
    jwtCookieName: 'jwt-cookie'
    jwtSecret: back-gammon-socket-game

server:
  port: 8081

rt-server:
  port: '9092'
  host: localhost

